# Generated by Django 2.1.1 on 2018-09-09 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TourismPlaces', '0006_auto_20171223_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismplace',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_for', to='TourismPlaces.Image'),
        ),
        migrations.AlterField(
            model_name='tourismplace',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_for', to='TourismPlaces.Video'),
        ),
    ]
