# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourismPlaces', '0003_auto_20171210_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourismplace',
            name='category',
        ),
    ]
