# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismPlaces', '0004_remove_tourismplace_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourismplace',
            name='place_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
