# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='places_pictures', width_field='width_field')),
                ('height_field', models.IntegerField(default=450)),
                ('width_field', models.IntegerField(default=350)),
            ],
        ),
        migrations.CreateModel(
            name='TourismPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='tourism_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourismPlaces.TourismPlace'),
        ),
    ]
