# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TourismPlaces', '0004_auto_20171203_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourismplace',
            name='image',
        ),
    ]
