# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourismPlaces', '0006_tourismplace_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tourism_place',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
